USE [master]
GO

/****** Object:  Database [testdevrdbms]    Script Date: 8/12/2025 1:20:07 PM ******/
DROP DATABASE [testdevrdbms]
GO

/****** Object:  Database [testdevrdbms]    Script Date: 8/12/2025 1:20:07 PM ******/
CREATE DATABASE [testdevrdbms]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'testdevrdbms', FILENAME = N'C:\Users\Administrator\testdevrdbms.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'testdevrdbms_log', FILENAME = N'C:\Users\Administrator\testdevrdbms_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [testdevrdbms].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [testdevrdbms] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [testdevrdbms] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [testdevrdbms] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [testdevrdbms] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [testdevrdbms] SET ARITHABORT OFF 
GO

ALTER DATABASE [testdevrdbms] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [testdevrdbms] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [testdevrdbms] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [testdevrdbms] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [testdevrdbms] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [testdevrdbms] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [testdevrdbms] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [testdevrdbms] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [testdevrdbms] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [testdevrdbms] SET  DISABLE_BROKER 
GO

ALTER DATABASE [testdevrdbms] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [testdevrdbms] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [testdevrdbms] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [testdevrdbms] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [testdevrdbms] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [testdevrdbms] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [testdevrdbms] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [testdevrdbms] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [testdevrdbms] SET  MULTI_USER 
GO

ALTER DATABASE [testdevrdbms] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [testdevrdbms] SET DB_CHAINING OFF 
GO

ALTER DATABASE [testdevrdbms] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [testdevrdbms] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [testdevrdbms] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [testdevrdbms] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [testdevrdbms] SET QUERY_STORE = OFF
GO

ALTER DATABASE [testdevrdbms] SET  READ_WRITE 
GO


